@echo off
:loop
echo Updating from git's http remote...
git fetch http
git reset --hard http/master
echo checking npm dependencies...
cmd /c npm install
echo Starting Wallace...
title Wallace
node main.js
echo Pausing for 30 seconds to restart...
PING 1.1.1.1 -n 1 -w 30000 >NUL
goto loop
